### ISSUE TITLE
`UnliftStrategy` not working

### ISSUE THREAD

**Issue by evanrelf** [haskell-effectful/effectful#71] opened 2022-07-19 06:22 UTC
I can't seem to get `effectful`'s `UnliftStrategy` to work with `streamly`. The following program fails with the error below:

```haskell
import Data.Function ((&))
import Effectful
import qualified Streamly.Prelude as Streamly

main :: IO ()
main = do
  (do x <- Streamly.fromList [1 .. 100 :: Int]; pure x)
  & Streamly.fromAsync
  & Streamly.drain
  & withUnliftStrategy (ConcUnlift Ephemeral Unlimited)
  & void
  & runEff
```

```
foo: If you want to use the unlifting function to run Eff computations in multiple threads, have a look at UnliftStrategy (ConcUnlift).
CallStack (from HasCallStack):
  error, called at src/Effectful/Internal/Unlift.hs:110:12 in effectful-core-1.0.0.0-Hrq7NNtVw4o5CC6HM1hRQt:Effectful.Internal.Unlift
  seqUnlift, called at src/Effectful/Internal/Monad.hs:189:20 in effectful-core-1.0.0.0-Hrq7NNtVw4o5CC6HM1hRQt:Effectful.Internal.Monad
  seqUnliftIO, called at src/Effectful/Internal/Monad.hs:177:35 in effectful-core-1.0.0.0-Hrq7NNtVw4o5CC6HM1hRQt:Effectful.Internal.Monad
  withEffToIO, called at src/Effectful/Internal/Monad.hs:301:18 in effectful-core-1.0.0.0-Hrq7NNtVw4o5CC6HM1hRQt:Effectful.Internal.Monad
```

It fails with both `Ephemeral` and `Persistent`.

I found that enabling `ApplicativeDo` gets rid of the error in that example program, so I suspect the problem is related to `streamly`'s implementation of `>>=` for `AsyncT`.

This is using `effectful` 1.0.0.0 and `streamly` 0.8.1.1, with GHC 9.0.2, running on macOS.

Sorry for the poor title, feel free to rename.

**Comment by Kleidukos** [comment] 2022-07-19 06:57
@evanrelf Hi! Looks like you may find an answer here: https://github.com/haskell-effectful/effectful/issues/69 :)

**Comment by arybczak** [comment] 2022-07-19 11:32
It's a duplicate of #69.

https://hackage.haskell.org/package/effectful-core-1.1.0.0/changelog

**Closed by arybczak** 2022-07-19 11:32 UTC

**Comment by evanrelf** [comment] 2022-07-19 15:38
Whoops, my bad 🙃 Thanks
